"""One-shot testnet setup / recovery.

Run this whenever the dev node has been reset (it wipes all contract state):

    .venv/bin/python scripts/setup_testnet.py

It will:
  1. Redeploy + wire all six PNS contracts (scripts/deploy_pns.py), which
     rewrites scripts/pns_addresses.json and tops up rent.
  2. Update app/.env.local with the fresh testnet contract addresses,
     PRESERVING any other keys you already have there (Privy app id,
     mainnet addresses, etc.).
  3. Seed a couple of demo names (alice.pot, bob.pot) so the Look-up flow
     has something to resolve. Pass --no-seed to skip.

The faucet (app /api/faucet) funds users from //Alice and needs no setup.
"""

import subprocess
import sys
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ADDRESSES = REPO_ROOT / "scripts" / "pns_addresses.json"
ENV_LOCAL = REPO_ROOT / "app" / ".env.local"
PY = sys.executable

# pns_addresses.json key -> app env var name (testnet)
ENV_MAP = {
    "registry": "NEXT_PUBLIC_PNS_REGISTRY",
    "pot_registrar": "NEXT_PUBLIC_PNS_POT_REGISTRAR",
    "registrar_controller": "NEXT_PUBLIC_PNS_REGISTRAR_CONTROLLER",
    "public_resolver": "NEXT_PUBLIC_PNS_PUBLIC_RESOLVER",
    "reverse_registrar": "NEXT_PUBLIC_PNS_REVERSE_REGISTRAR",
    "subname_registrar": "NEXT_PUBLIC_PNS_SUBNAME_REGISTRAR",
}


def run(args: list[str]) -> None:
    print(f"\n$ {' '.join(args)}")
    subprocess.run(args, cwd=REPO_ROOT, check=True)


def parse_env(path: Path) -> dict[str, str]:
    """Read KEY=VALUE lines into a dict (comments/blank lines ignored)."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for line in path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        out[k.strip()] = v.strip()
    return out


def write_env(path: Path, env: dict[str, str]) -> None:
    """Write .env.local in tidy sections, preserving non-testnet keys."""
    testnet_keys = ["NEXT_PUBLIC_PORTALDOT_WSS", *ENV_MAP.values()]
    mainnet_keys = [k for k in env if "MAINNET" in k]
    privy_keys = [k for k in env if "PRIVY" in k]
    known = set(testnet_keys) | set(mainnet_keys) | set(privy_keys)
    other = [k for k in env if k not in known]

    lines: list[str] = ["# Regenerated by scripts/setup_testnet.py", ""]
    lines.append("# Testnet (Portaldot dev node)")
    for k in testnet_keys:
        lines.append(f"{k}={env.get(k, '')}")
    if privy_keys:
        lines += ["", "# Privy"]
        for k in privy_keys:
            lines.append(f"{k}={env[k]}")
    if mainnet_keys:
        lines += ["", "# Mainnet"]
        for k in sorted(mainnet_keys):
            lines.append(f"{k}={env[k]}")
    if other:
        lines += ["", "# Other"]
        for k in other:
            lines.append(f"{k}={env[k]}")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    seed = "--no-seed" not in sys.argv

    # 1. redeploy + wire (rewrites pns_addresses.json)
    run([PY, "scripts/deploy_pns.py"])

    # 2. merge fresh addresses into app/.env.local, preserving other keys
    addrs = json.loads(ADDRESSES.read_text())
    env = parse_env(ENV_LOCAL)
    env.setdefault(
        "NEXT_PUBLIC_PORTALDOT_WSS",
        "wss://portaldot.philotheephilix.in",
    )
    for json_key, env_key in ENV_MAP.items():
        if json_key in addrs:
            env[env_key] = addrs[json_key]
    write_env(ENV_LOCAL, env)
    print(f"\nwrote {ENV_LOCAL} (preserved {sum('PRIVY' in k for k in env)} Privy "
          f"+ {sum('MAINNET' in k for k in env)} mainnet keys)")

    # 3. seed demo names
    if seed:
        for name, uri in (("alice", "//Alice"), ("bob", "//Bob")):
            try:
                run([PY, "scripts/create_name.py", name, uri])
            except subprocess.CalledProcessError as e:
                print(f"  (seed {name}.pot failed: {e}; continuing)")
    else:
        print("\nskipped demo-name seeding (--no-seed)")

    print("\n✅ testnet ready. Restart the dApp dev server to pick up "
          "the new .env.local.")


if __name__ == "__main__":
    main()
