"""Cross-language conformance check against the same JSON vectors used by
the TypeScript SDK. Source: packages/sdk-ts/test/vectors/namehash.json,
generated by scripts/gen_test_vectors.py.
"""
import json
import os
import unittest

from portal_name import labelhash, namehash, normalize, try_normalize

VECTORS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "sdk-ts", "test", "vectors",
    "namehash.json",
)


def hexstr(b: bytes) -> str:
    return "0x" + b.hex()


class HashConformance(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(VECTORS_PATH) as f:
            cls.vectors = json.load(f)

    def test_labelhash_matches_ts(self):
        for case in self.vectors["labelhash"]:
            self.assertEqual(hexstr(labelhash(case["label"])), case["hash"])

    def test_namehash_root(self):
        self.assertEqual(namehash(""), b"\x00" * 32)

    def test_namehash_matches_ts(self):
        for case in self.vectors["namehash"]:
            self.assertEqual(hexstr(namehash(case["name"])), case["node"])


class NormalizeConformance(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(VECTORS_PATH) as f:
            cls.vectors = json.load(f)

    def test_normalize_cases(self):
        for case in self.vectors["normalize"]:
            with self.subTest(name=case["name"]):
                if case["expected"] is None:
                    self.assertIsNone(try_normalize(case["input"]))
                else:
                    self.assertEqual(normalize(case["input"]), case["expected"])

    def test_normalize_idempotent(self):
        for case in self.vectors["normalize"]:
            if case["expected"] is None:
                continue
            once = normalize(case["input"])
            twice = normalize(once)
            self.assertEqual(once, twice)


if __name__ == "__main__":
    unittest.main()
